export const firebaseConfig = {
  apiKey: "AIzaSyBtV479SVRsY_jYZLtlBjl-MOvGZ32U6yE",
  authDomain: "parthunt.firebaseapp.com",
  projectId: "parthunt",
  storageBucket: "parthunt.firebasestorage.app",
  messagingSenderId: "1089089473351",
  appId: "1:1089089473351:web:f136191bbbd131abdf5a62",
  measurementId: "G-W107HW9C4K",
};

export const popularVehicleMakes = {
  Audi: ["A1", "A3", "A4", "A5", "A6", "Q2", "Q3", "Q5", "Q7", "TT"],
  BMW: ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "X1", "X3", "X5", "i3", "i4"],
  Citroen: ["C1", "C3", "C4", "C4 Picasso", "Berlingo", "DS3"],
  Fiat: ["500", "Panda", "Tipo", "Punto", "Doblo"],
  Ford: ["Fiesta", "Focus", "Kuga", "Mondeo", "Puma", "Transit", "Transit Custom", "C-Max", "S-Max"],
  Honda: ["Civic", "Jazz", "CR-V", "HR-V", "Accord"],
  Hyundai: ["i10", "i20", "i30", "Tucson", "Kona", "Santa Fe"],
  Jaguar: ["XE", "XF", "F-Pace", "E-Pace", "I-Pace"],
  Kia: ["Picanto", "Rio", "Ceed", "Sportage", "Niro", "Sorento"],
  "Land Rover": ["Range Rover", "Range Rover Sport", "Range Rover Evoque", "Discovery", "Discovery Sport", "Defender", "Freelander"],
  Lexus: ["CT", "IS", "IS 300h", "ES", "NX", "RX", "UX"],
  Mazda: ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-5", "MX-5"],
  "Mercedes-Benz": ["A-Class", "B-Class", "C-Class", "E-Class", "S-Class", "CLA", "GLA", "GLC", "GLE", "Sprinter"],
  Mini: ["Hatch", "Clubman", "Countryman", "Convertible", "Paceman"],
  Nissan: ["Micra", "Juke", "Qashqai", "X-Trail", "Leaf", "Navara"],
  Peugeot: ["108", "208", "308", "508", "2008", "3008", "5008", "Partner"],
  Renault: ["Clio", "Megane", "Captur", "Kadjar", "Scenic", "Trafic"],
  Seat: ["Ibiza", "Leon", "Ateca", "Arona", "Alhambra"],
  Skoda: ["Fabia", "Octavia", "Superb", "Yeti", "Karoq", "Kodiaq"],
  Toyota: ["Aygo", "Yaris", "Corolla", "Auris", "Prius", "C-HR", "RAV4", "Hilux"],
  Vauxhall: ["Corsa", "Astra", "Insignia", "Mokka", "Grandland", "Crossland", "Zafira", "Vivaro"],
  Volkswagen: ["Polo", "Golf", "Passat", "Tiguan", "T-Roc", "Touran", "Transporter", "Caddy"],
  Volvo: ["V40", "V60", "V90", "XC40", "XC60", "XC90", "S60"],
};

export const popularVehicleVariants = {
  Ford: {
    Fiesta: [
      { name: "Style", from: 2012, to: 2017 },
      { name: "Zetec", from: 2012 },
      { name: "Titanium", from: 2012 },
      { name: "ST-Line", from: 2017 },
      { name: "Active", from: 2018 },
    ],
    Focus: [
      { name: "Edge", from: 2012, to: 2018 },
      { name: "Zetec", from: 2012 },
      { name: "Titanium", from: 2012 },
      { name: "ST-Line", from: 2016 },
      { name: "Vignale", from: 2018 },
    ],
    Kuga: [
      { name: "Zetec", from: 2012 },
      { name: "Titanium", from: 2012 },
      { name: "ST-Line", from: 2017 },
      { name: "Vignale", from: 2016 },
    ],
  },
  Lexus: {
    CT: [
      { name: "CT 200h", from: 2012, to: 2020 },
      { name: "Advance", from: 2012, to: 2020 },
      { name: "F Sport", from: 2012, to: 2020 },
      { name: "Premier", from: 2012, to: 2020 },
    ],
    IS: [
      { name: "IS 250", from: 2012, to: 2015 },
      { name: "IS 300h", from: 2013 },
      { name: "Luxury", from: 2013 },
      { name: "F Sport", from: 2013 },
      { name: "Premier", from: 2013 },
    ],
    "IS 300h": [
      { name: "Luxury", from: 2013 },
      { name: "Advance", from: 2013 },
      { name: "F Sport", from: 2013 },
      { name: "Takumi", from: 2019 },
      { name: "Premier", from: 2013, to: 2020 },
    ],
    NX: [
      { name: "NX 300h", from: 2014, to: 2021 },
      { name: "NX 350h", from: 2021 },
      { name: "F Sport", from: 2014 },
      { name: "Takumi", from: 2018 },
    ],
  },
  Toyota: {
    Yaris: [
      { name: "Icon", from: 2012 },
      { name: "Design", from: 2012 },
      { name: "Excel", from: 2012 },
      { name: "GR Sport", from: 2021 },
    ],
    Corolla: [
      { name: "Icon", from: 2019 },
      { name: "Design", from: 2019 },
      { name: "Excel", from: 2019 },
      { name: "GR Sport", from: 2020 },
    ],
    Prius: [
      { name: "Active", from: 2012, to: 2016 },
      { name: "Business Edition", from: 2016 },
      { name: "Excel", from: 2016 },
    ],
  },
  BMW: {
    "3 Series": [
      { name: "SE", from: 2012 },
      { name: "Sport", from: 2012 },
      { name: "Luxury", from: 2012, to: 2019 },
      { name: "M Sport", from: 2012 },
      { name: "330e", from: 2016 },
    ],
  },
  "Mercedes-Benz": {
    "C-Class": [
      { name: "SE", from: 2012 },
      { name: "Sport", from: 2012 },
      { name: "AMG Line", from: 2015 },
      { name: "Premium", from: 2015 },
      { name: "Premium Plus", from: 2015 },
    ],
  },
  Volkswagen: {
    Golf: [
      { name: "S", from: 2012 },
      { name: "SE", from: 2012 },
      { name: "Match", from: 2012 },
      { name: "GT", from: 2012 },
      { name: "R-Line", from: 2015 },
      { name: "GTE", from: 2015 },
    ],
  },
};

export const demoPlatforms = [
  {
    id: "ebay",
    slug: "ebay",
    name: "eBay",
    category: "Online marketplace",
    categoryKey: "online_marketplace",
    websiteUrl: "https://www.ebay.co.uk/",
    logoUrl: "/assets/platforms/ebay.svg",
    coverImageUrl: "",
    averageRating: 4.3,
    reviewCount: 214,
    successfulPurchaseCount: 182,
    averageItemRating: 4.2,
    averageDeliveryRating: 4.1,
    wouldBuyAgainPercentage: 78,
    topPartCategories: ["Body panels", "Headlights", "Mirrors"],
    summary: "Wide choice and competitive prices, but condition varies by seller.",
  },
  {
    id: "breakerlink",
    slug: "breakerlink",
    name: "BreakerLink",
    category: "Breaker yard",
    categoryKey: "breaker_yard",
    websiteUrl: "https://www.breakerlink.com/",
    logoUrl: "/assets/platforms/breakerlink.svg",
    coverImageUrl: "",
    averageRating: 4.5,
    reviewCount: 126,
    successfulPurchaseCount: 119,
    averageItemRating: 4.5,
    averageDeliveryRating: 4.3,
    wouldBuyAgainPercentage: 84,
    topPartCategories: ["Bumpers", "Gearboxes", "Doors"],
    summary: "Useful for getting quotes from multiple breakers without searching yard by yard.",
  },
  {
    id: "1st-choice-spares",
    slug: "1st-choice-spares",
    name: "1st Choice Spares",
    category: "Car parts retailer",
    categoryKey: "car_parts_retailer",
    websiteUrl: "https://www.1stchoice.co.uk/",
    logoUrl: "/assets/platforms/first-choice-spares.svg",
    coverImageUrl: "",
    averageRating: 4.1,
    reviewCount: 98,
    successfulPurchaseCount: 91,
    averageItemRating: 4.1,
    averageDeliveryRating: 4.0,
    wouldBuyAgainPercentage: 74,
    topPartCategories: ["Alternators", "ECUs", "Interior parts"],
    summary: "Good for quote-led searches, especially when exact part names are unclear.",
  },
  {
    id: "parts-gateway",
    slug: "parts-gateway",
    name: "Parts Gateway",
    category: "Specialist parts supplier",
    categoryKey: "specialist_parts_supplier",
    websiteUrl: "https://www.partsgateway.co.uk/",
    logoUrl: "/assets/platforms/parts-gateway.svg",
    coverImageUrl: "",
    averageRating: 4.2,
    reviewCount: 87,
    successfulPurchaseCount: 76,
    averageItemRating: 4.2,
    averageDeliveryRating: 4.2,
    wouldBuyAgainPercentage: 80,
    topPartCategories: ["Engines", "Radiators", "Lights"],
    summary: "Strong for tested used parts and supplier-backed compatibility checks.",
  },
  {
    id: "local-scrap-yard",
    slug: "local-scrap-yard",
    name: "Local Scrap Yard",
    category: "Scrap yard",
    categoryKey: "scrap_yard",
    websiteUrl: "",
    logoUrl: "/assets/platforms/local-scrap-yard.svg",
    coverImageUrl: "",
    averageRating: 3.9,
    reviewCount: 64,
    successfulPurchaseCount: 58,
    averageItemRating: 4.0,
    averageDeliveryRating: 3.6,
    wouldBuyAgainPercentage: 68,
    topPartCategories: ["Wheels", "Doors", "Tail lights"],
    summary: "Best when users can inspect parts in person and confirm mounts or colour.",
  },
  {
    id: "independent-breaker-yard",
    slug: "independent-breaker-yard",
    name: "Independent Breaker Yard",
    category: "Breaker yard",
    categoryKey: "breaker_yard",
    websiteUrl: "",
    logoUrl: "/assets/platforms/independent-breaker-yard.svg",
    coverImageUrl: "",
    averageRating: 4.0,
    reviewCount: 42,
    successfulPurchaseCount: 39,
    averageItemRating: 4.0,
    averageDeliveryRating: 3.9,
    wouldBuyAgainPercentage: 72,
    topPartCategories: ["Bonnet", "Seats", "Exhaust"],
    summary: "Often helpful for older vehicles and parts not listed on larger platforms.",
  },
];

export const parts = [
  {
    id: "front-bumper",
    name: "Front bumper",
    category: "Exterior",
    alternativeNames: ["Front bumper cover", "Front bumper assembly", "Front bumper skin", "Front valance"],
    compatibilityNotes: ["Confirm facelift/pre-facelift", "Check parking sensor holes", "Match body style", "Inspect cracks and mounts"],
  },
  {
    id: "bonnet",
    name: "Bonnet",
    category: "Exterior",
    alternativeNames: ["Hood", "Engine lid", "Bonnet panel"],
    compatibilityNotes: ["Check colour code", "Confirm year range", "Inspect hinges", "Ask about dents"],
  },
  {
    id: "headlights",
    name: "Headlights",
    category: "Exterior",
    alternativeNames: ["Headlamp", "Front light unit", "Headlight cluster"],
    compatibilityNotes: ["Confirm side", "Check halogen/xenon/LED", "Confirm LHD/RHD", "Inspect tabs and lens"],
  },
  {
    id: "wing-mirrors",
    name: "Wing mirrors",
    category: "Exterior",
    alternativeNames: ["Door mirror", "Side mirror", "Mirror assembly"],
    compatibilityNotes: ["Confirm left or right", "Check power fold", "Check indicator type", "Match connector pins"],
  },
  {
    id: "engine",
    name: "Engine",
    category: "Engine bay",
    alternativeNames: ["Engine assembly", "Bare engine", "Complete engine", "Motor"],
    compatibilityNotes: ["Confirm engine code", "Ask mileage", "Check warranty", "Confirm included ancillaries"],
  },
  {
    id: "battery",
    name: "Battery",
    category: "Engine bay",
    alternativeNames: ["Car battery", "12V battery", "Starter battery"],
    compatibilityNotes: ["Check battery type", "Match Ah and CCA", "Confirm start-stop support", "Check age"],
  },
  {
    id: "radiator",
    name: "Radiator",
    category: "Engine bay",
    alternativeNames: ["Cooling radiator", "Engine radiator", "Rad pack"],
    compatibilityNotes: ["Match engine", "Check manual/automatic", "Inspect leaks", "Confirm AC condenser separate"],
  },
  {
    id: "gearbox",
    name: "Gearbox",
    category: "Undercarriage",
    alternativeNames: ["Transmission", "Manual gearbox", "Automatic gearbox"],
    compatibilityNotes: ["Confirm gearbox code", "Match engine", "Ask mileage", "Check warranty"],
  },
  {
    id: "exhaust",
    name: "Exhaust",
    category: "Undercarriage",
    alternativeNames: ["Exhaust pipe", "Back box", "Exhaust system"],
    compatibilityNotes: ["Confirm engine", "Check section needed", "Inspect corrosion", "Match body type"],
  },
  {
    id: "dashboard",
    name: "Dashboard",
    category: "Interior",
    alternativeNames: ["Dash", "Dashboard assembly", "Dash panel"],
    compatibilityNotes: ["Check airbag compatibility", "Match trim colour", "Confirm RHD/LHD", "Inspect mounts"],
  },
];

export const demoResults = [
  {
    id: "res-ebay-123456789",
    title: "2017 Ford Focus front bumper cover with parking sensor holes",
    description: "Used bumper cover with clear seller photos. Check colour code and facelift fitment.",
    imageUrl: "/assets/results/front-bumper-ebay.svg",
    price: "£86",
    source: "eBay",
    platformId: "ebay",
    platformName: "eBay",
    platformCategory: "Online marketplace",
    listingUrl: "https://www.ebay.co.uk/itm/123456789",
    originalDomain: "ebay.co.uk",
    condition: "Used",
    location: "Manchester",
    delivery: true,
    confidenceLabel: "High match",
  },
  {
    id: "res-breakerlink-quote-456",
    title: "Ford Focus 2017 front bumper quote from UK breaker",
    description: "Breaker quote result with delivery available. Ask for sensor and grille compatibility.",
    imageUrl: "/assets/results/front-bumper-breaker.svg",
    price: "£95",
    source: "BreakerLink",
    platformId: "breakerlink",
    platformName: "BreakerLink",
    platformCategory: "Breaker yard",
    listingUrl: "https://www.breakerlink.com/parts/ford/focus/front-bumper/quote-456",
    originalDomain: "breakerlink.com",
    condition: "Used",
    location: "Birmingham",
    delivery: true,
    confidenceLabel: "High match",
  },
  {
    id: "res-parts-gateway-789",
    title: "Ford Focus front bumper assembly tested recycled part",
    description: "Supplier-backed listing. Confirm trim, sensor holes, and body type before buying.",
    imageUrl: "/assets/results/front-bumper-recycled.svg",
    price: "£129",
    source: "Parts Gateway",
    platformId: "parts-gateway",
    platformName: "Parts Gateway",
    platformCategory: "Specialist parts supplier",
    listingUrl: "https://www.partsgateway.co.uk/parts/detail/ford-focus-front-bumper-789",
    originalDomain: "partsgateway.co.uk",
    condition: "Refurbished",
    location: "Leeds",
    delivery: true,
    confidenceLabel: "Possible match",
  },
];
